# Generated by Django 5.0.6 on 2024-06-22 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CollegeData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Category', models.CharField(max_length=100)),
                ('Status', models.CharField(max_length=100)),
                ('University', models.CharField(max_length=100)),
                ('Home_university', models.CharField(max_length=100)),
                ('College_code', models.IntegerField()),
                ('College_name', models.CharField(max_length=100)),
                ('Rank', models.IntegerField()),
                ('Percentile', models.FloatField()),
            ],
        ),
    ]
